"use strict";

// All UI texts. You can translate whole UI by modifying these values.
module.exports = {
  ui: {
    newGame: "Neues Spiel",
    throwDice: "Würfeln",
    highScores: "High Scores",
    ones: "Einer",
    twos: "Zweier",
    threes: "Dreier",
    fours: "Vierer",
    fives: "Fünfer",
    sixes: "Sechser",
    bonus: "Bonus",
    onePair: "1 Paar",
    twoPairs: "2 Paar",
    threeOfAKind: "3 of a Kind",
    fourOfAKind: "4 of a Kind",
    smallStraight: "Small Straight",
    largeStraight: "Large Straight",
    fullHouse: "Full House",
    chance: "Chance",
    yatzy: "Yatzy",
    combination: "Combination",
    score: "Score",
    total: "Total Score",
    back: "Back to Game",
    round: "Round",
    throwRound: "Wurf",
    player1Name: "Spieler 1 Name",
    player2Name: "Spieler 2 Name",
    player3Name: "Spieler 3 Name",
    player4Name: "Spieler 4 Name",
    player1Type: "Spieler 1 Type",
    player2Type: "Spieler 2 Type",
    player3Type: "Spieler 3 Type",
    player4Type: "Spieler 4 Type",
    player: "Spieler",
    playerName: "Spielername",
    playerType: "Spieler Typ",
    numberOfPlayers: "Spieleranzahl",
    select: "wählen",
    totalRounds: 15,
    totalThrows: 3,
    human: "Mensch",
    ai: "Bot",
    ai_real_name: "Esko",
    ai_real_name_2: "Harry,Ross,Bruce,Cook,Carolyn,Morgan,Albert,Walker,Randy,Reed,Larry,Barnes,Lois,Wilson,Jesse,Campbell,Ernest,Rogers,Theresa,Patterson,Henry,Simmons,Michelle,Perry,Frank,Butler,Shirley",
    ai_message_1: "PLEASE WAIT ... Esko starts new round",
    ai_message_2: "PLEASE WAIT ... Esko throws dice",
    ai_message_3: "PLEASE WAIT ... Esko selects which dice to throw again",
    ai_message_4: "PLEASE WAIT ... Esko selects"
  }
};
